### ISSUE TITLE
send notification to case owner when case is finished

### ISSUE THREAD

**Issue by cosven** [pingcap/tipocket#329]
**Background**

 [tpctl](https://github.com/cosven/tidb-testing/tree/master/tipocket-ctl)  can generate `argo workflow` for tipocket test case. 
In the workflow, notification is sent to case owner before case starts and after case ends.

<details>
 <summary>For example:</summary>

```yaml
metadata:
  generateName: tpctl-pipelined-locking-
  namespace: argo
spec:
  entrypoint: main
  onExit: on-exit
  templates:
  - name: main
    steps:
    - - arguments:
          parameters:
          - name: stage
            value: running
          - name: status
            value: passed
        name: notify-start
        template: notify
    - - name: pipelined-locking
        template: pipelined-locking
  - name: on-exit
    steps:
    - - arguments:
          parameters:
          - name: stage
            value: end
          - name: status
            value: failed
        name: notify-end-failed
        template: notify
        when: '{{workflow.status}} != Succeeded'
      - arguments:
          parameters:
          - name: stage
            value: end
          - name: status
            value: passed
        name: notify-end-passed
        template: notify
        when: '{{workflow.status}} == Succeeded'
  - container:
      args:
      - '@xxx,@yyy'
      - pipelined-locking
      - '{{workflow.name}}'
      - '{{inputs.parameters.stage}}'
      - --status
      - '{{inputs.parameters.status}}'
      - --cmd
      - L2Jpbi9waXBlbGluZWQtbG9ja2luZyAtdGlrdi1jb25maWc9Ii9jb25maWcvdHBjdGwtdGlrdi50b21sIiAtaHViPSJodWIucGluZ2NhcC5uZXQiIC1yZXBvc2l0b3J5PSJxYSIgLWltYWdlLXZlcnNpb249Im1hc3Rlci1mYWlscG9pbnQiIC1jbGllbnQ9IjEiIC1ydW4tdGltZT0iMTBoIiAtbmFtZXNwYWNlPSJ0cGN0bC1waXBsaW5lZC1sb2NraW5nIiAtY29udGVuZGVycz0iMSIgLXN0cmljdD0idHJ1ZSIgLW5lbWVzaXM9IiIgLXB1cmdlPSJmYWxzZSIgLXRpa3YtaW1hZ2U9IiIgLXRpZGItaW1hZ2U9IiIgLXBkLWltYWdlPSIiIC10aWRiLWNvbmZpZz0iIiAtcGQtY29uZmlnPSIiIC10aWt2LXJlcGxpY2FzPSI1IiAtdGlkYi1yZXBsaWNhcz0iMSIgLXBkLXJlcGxpY2FzPSIxIiAtc3RvcmFnZS1jbGFzcz0ibG9jYWwtc3RvcmFnZSIgLWxva2ktYWRkcj0iaHR0cDovL2dhdGV3YXkubG9raS5zdmMiIC1sb2tpLXVzZXJuYW1lPSJsb2tpIiAtbG9raS1wYXNzd29yZD0iYWRtaW4i
      - --tidbcluster
      - cGQ6CiAgY29uZmlnOiAnJwogIGltYWdlOiBodWIucGluZ2NhcC5uZXQvcWEvcGQ6bWFzdGVyLWZhaWxwb2ludAogIG5hbWU6IHBkCiAgcmVwbGlhY3M6ICcxJwp0aWRiOgogIGNvbmZpZzogJycKICBpbWFnZTogaHViLnBpbmdjYXAubmV0L3FhL3RpZGI6bWFzdGVyLWZhaWxwb2ludAogIG5hbWU6IHRpZGIKICByZXBsaWFjczogJzEnCnRpa3Y6CiAgY29uZmlnOiB8CiAgICBbcGVzc2ltaXN0aWMtdHhuXQogICAgcGlwZWxpbmVkID0gdHJ1ZQogIGltYWdlOiBodWIucGluZ2NhcC5uZXQvcWEvdGlrdjptYXN0ZXItZmFpbHBvaW50CiAgbmFtZTogdGlrdgogIHJlcGxpYWNzOiAnNScK
      env:
      - name: SLACK_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            key: token
            name: tipocket-slack-token
      image: hub.ppp.net/tpctl/notify
      imagePullpolicy: Always
      name: notify-py
    inputs:
      parameters:
      - name: stage
      - default: passed
        name: status
    name: notify
  - container:
      command:
      - sh
      - -c
      - /bin/pipelined-locking -tikv-config="/config/tpctl-tikv.toml" -hub="hub.ppp.net"
        -repository="qa" -image-version="master-failpoint" -client="1" -run-time="10h"
        -namespace="tpctl-piplined-locking" -contenders="1" -strict="true" -nemesis=""
        -purge="false" -tikv-image="" -tidb-image="" -pd-image="" -tidb-config=""
        -pd-config="" -tikv-replicas="5" -tidb-replicas="1" -pd-replicas="1" -storage-class="local-storage"
        -loki-addr="http://gateway.loki.svc" -loki-username="loki" -loki-password="admin"
      image: hub.ppp.net/tpctl/tipocket:pipelined-locking
      imagePullpolicy: Always
      name: pipelined-locking
    metadata:
      labels:
        ns: tpctl-piplined-locking
    name: pipelined-locking
```
</details>

However, tipocket test case daily-run use `argo cron workflow` and tpctl can't generate argo cron workflow temporarily.

**TODO**

- [x] make tpctl generate argo cron workflow
- [x] argo cron workflow for pipelined-locking
